config/routes.rb
Blockbuster::Application.routes.draw do

  root :to => 'posts#index'

  resources :posts do
    resources :comments, :only => [:create] do
      member do
        post "like", to: "comments#upvote"
        post "dislike", to: "comments#downvote"
      end
    end
    member do
      post "like", to: "posts#upvote"
      post "dislike", to: "posts#downvote"
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  	belongs_to :post
  	has_many :votes
  	validates_presence_of :body
  	
	def downvotes
		self.votes.where(upvote: false).count
	end

	def upvotes
		self.votes.where(upvote: true).count
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	has_many :votes
  	validates_presence_of :body
  	LOCATIONS = ['The Block on 25th East & West', 
			    'The Block on 28th', 
			    'The Block on Leon', 
			    'The Block on 23rd', 
			    'The Block on Pearl North & South', 
			    'The Block on Rio Grande']


	def downvotes
		self.votes.where(upvote: false).count
	end

	def upvotes
		self.votes.where(upvote: true).count
	end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  belongs_to :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    if params[:comment][:body].length != 0
      @comment = @post.comments.create!(params[:comment].permit(:body))
      redirect_to @post
    else
      redirect_to @post
    end
  end

  def downvote
    @comment = Comment.find(params[:id])
    @comment.votes.create(upvote: false)
    render :nothing => true, :status => 200, :content_type => 'text/html'
  end

  def upvote
    @comment = Comment.find(params[:id])
    @comment.votes.create(upvote: true)
    render :nothing => true, :status => 200, :content_type => 'text/html'
  end

  def downvotes
    @comment = Comment.find(params[:id])
    @comment.votes.where(upvote: false)
  end

  def upvotes
    @comment = Comment.find(params[:id])
    @comment.votes.where(upvote: true)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:edit, :update]
  helper_method :downvote
  helper_method :upvote  

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @posts = @posts.sort_by{|e| -e.upvotes}
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        session[:post_ids] ||= []
        session[:post_ids] << @post.id
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def downvote
    @post = Post.find(params[:id])
    @post.votes.create(upvote: false)
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Your vote was recorded.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.votes.create(upvote: true)
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Your vote was recorded.' }
      format.json { head :no_content }
    end
  end

  private
    # Make sure comment can only be edited or updated in same session it was created in
    def authorize
      unless session[:post_ids] && session[:post_ids].include?(params[:id].to_i)
        redirect_to root_url
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
    <div class="row"> 
    	<div class="col-md-2"></div>
    	<div class="col-md-2">
	    	<h4 style="display: inline-block;">
				<%= link_to '' , like_post_comment_path(@post, comment), :method=>:post, :remote => true, :class => "fa fa-arrow-up"%>
				</i> <%= comment.upvotes %>
				<%= link_to '' , dislike_post_comment_path(@post, comment), :method=>:post, :remote => true, :class => "fa fa-arrow-down"%>
				</i> <%= comment.downvotes %>
				<i>&nbsp;</i>
			</h4>
		</div>
		<div class="col-md-8" style="margin-left: -6em; margin-bottom:1em;">
	        <h4>
	            <%= comment.body %>
	        </h4>
        </div>
    </div>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blockbuster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
  <a class="navbar-brand" href="/">The Chopping Block</a>
  <p class="navbar-text navbar-right"><a href="mailto:eolszewski@gmail.com?Subject=Cool%20Site" target="_top" class="navbar-link">Contact Us</a></p>
  </div>
</nav>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="row">
      <div class="col-md-2" style="display:inline-block;">
        <h3>
          <%= f.label :location %>
        </h3>
      </div>
      <div class="col-md-10" style="display:inline-block;">
        <h3>
          <%= f.select :location, options_for_select(Post::LOCATIONS), :class => "form-control" %>
        </h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2" style="display:inline-block;">
        <h3>
          <%= f.label :body %>
        </h3>
      </div>
      <div class="col-md-10" style="display:inline-block;">
        <h3>
          <%= f.text_area :body, :style => "resize:vertical; width: 100%; height: 5em;" %>
        </h3>
      </div>
    </div>
    
  </div>

  <%= f.submit :class => 'btn btn-primary pull-right' %>
<% end %>

app/views/posts/_post.html.erb
<div class="row">
	<div class="col-md-2" style="display: inline-block; text-align: center;">
		<h4 style="vertical-align: top; padding-top: 17px;">
			<%= link_to '' , like_post_path(post), :method=>:post, :remote => true, :class => "fa fa-arrow-up"%>
			</i> <%= post.upvotes %>
			<%= link_to '' , dislike_post_path(post), :method=>:post, :remote => true, :class => "fa fa-arrow-down"%>
			</i> <%= post.downvotes %>
			<br>
			<br>
			<i><%= post.comments.count %> comments</i>
		</h4>
	</div>
	<div class="col-md-10" style="display: inline-block;">
		<h2 style="display: inline-block; margin-bottom: 0;">
			<%= link_to_unless_current post.location, post %>
		</h2>
		<h4>
			<%= post.body %>
			 <% if session[:post_ids] && session[:post_ids].include?(post.id) %>
			 	<%= link_to 'Edit', edit_post_path(post), :class => "pull-right" %>	
			 <% end %>
		</h4>
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
 <%= render :partial => @posts %>
 <br>
 <br>
 <%= link_to 'New Post', new_post_path, :class => 'btn btn-primary pull-right', :style => 'color: white' %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
 <p id="notice"><%= notice %></p>

 <%= render :partial => @post %>

 <div id="comments">
    <%= render :partial => @post.comments %>
 </div>

<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-10">
		 <%= form_for [@post, Comment.new] do |f| %>
		    <p>
		        <%= f.label :body, "New comment" %><br/>
		        <%= f.text_area :body, :style => "resize:vertical; width: 100%; height:5em;" %>
		    </p>
		    <%= f.submit "Add comment", :class => 'btn btn-primary pull-right' %>
		<% end %>
	</div>
</div>